# Generated by Django 2.1 on 2018-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=32)),
                ('respondent', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=32)),
                ('createdOn', models.DateField(auto_now=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
