# Generated by Django 2.1 on 2018-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='respondent',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
